# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20171029_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
