# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('fish', 'fish'), ('bird', 'bird')], default='dog', max_length=10),
        ),
    ]
