# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20171029_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='AnimalType',
        ),
    ]
