# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20171031_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
