# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_animal_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='feeds',
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals_img'),
        ),
    ]
