# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20171031_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Animal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_animals', to='shop_app.Cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='animals',
            field=models.ManyToManyField(through='shop_app.OrderAnimal', to='shop_app.Animal'),
        ),
    ]
